runtime: php
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "8.2"
  document_root: public

skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

env_variables:
  APP_DEBUG: true
  APP_URL: "https://assumable-app.uc.r.appspot.com"
  APP_ENV: production
  APP_KEY: "base64:ctQUvIJcGE9acitSN1+6lDTe23kmEG9ScjwADz/uPPU="
  APP_NAME: "Assumable"

  LOG_LEVEL: debug

